name: Run tests

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python scripts/ci/install
    - name: Install Thundra Python Agent
      uses: thundra-io/thundra-foresight-python-action@action-experiment
      with:
        apikey: ${{ secrets.THUNDRA_APIKEY }}
        project_id: ${{ secrets.THUNDRA_PROJECT_ID }}
    - name: Run tests
      run: |
        python scripts/ci/run-tests
      env:
        THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.me/v1
        THUNDRA_AGENT_DEBUG_ENABLE: true
